### ISSUE TITLE
Please enable Github.io site

### ISSUE THREAD

**Issue by rdebath** [erans/dicepass#7]
The URL https://erans.github.io/dicepass/ can point to a website of this repository.
Would you make it work so I don't have to trust Netlify too.

**Comment by erans** [comment]
I personally know and trust Netlify.

But here you got: https://erans.github.io/dicepass/

Also, you can always clone and open the page locally, as it should work without a problem.

**Comment by rdebath** [comment]
> I personally know and trust Netlify.

Sorry, I was more thinking from the "paranoid" viewpoint where you minimise the number of "trusts" ie: entities that have the ability to break it. This has nothing to do with how "trustworthy" anybody is.

Anyway, I think I got it wrong, running it locally probably is more effective by that measure.
